version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Cardorium-Stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1gr3yy2gboiuy"
s3_prefix = "Cardorium-Stack"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
